### ISSUE TITLE
Tests on master are broken

### ISSUE THREAD

**Issue by vmx** [ipld/js-ipld-resolver#107]
Currently the tests don't pass due to https://github.com/ipfs/js-ipfs-repo/commit/27553a3d51ef5b2c98a21efb67e5fc12c4a8deb1. There's now a version mismatch between `ipfs-repo` and the example repository for the tests.

The solution is to recreate the example repository.

A workaround is to pin `ipfs-repo` to `0.17.0`.

**Comment by vmx** [comment]
@diasdavid Can you recreate the example repo with the most recent version of `ipfs-repo`? Please also put into the commit how you did it, so that I can do it myself the next time it is needed.

**Comment by VictorBjelkholm** [comment]
For the tests, we should probably have two different kinds of tests. The default set of tests generates the repo for use in the test cases, that way a version upgrade should go smooth. Other set of tests is testing with specific repo versions, which would break on every version upgrade.

**Comment by diasdavid** [comment]
Sorry about that @vmx. There was a go-ipfs repo update which doesn't affect how js-ipfs works other than the fact that js-ipfs checks for the version. 

I've updated the tests on #108 so that you don't hit this anymore.
