### ISSUE TITLE
example code bug

### ISSUE THREAD

**Issue by crazysoldier** [ipld/js-ipld-resolver#27]
working version:
const node = {
  hello: {
    world: 11,
    some: 12
  }
}
const mh = ipld.multihash(ipld.marshal(node))
ipldService.add(node, (err) => { resolve(ipldService, `${mh}/hello/world`, (err, res) => { console.log(res) })})

**Comment by crazysoldier** [comment]
this is the original which isnt working:

const node = {
  hello: {
    world: 11,
    some: 12
  }
}
const mh = ipld.multihash(ipld.marshal(node))
ipldService.add(node, (err) => {
  resolve(ipldService, `${mh}/hello/world`, (err, res) => {
  console.log(res)
  // => 11
})

**Comment by diasdavid** [comment]
@crazysoldier want to look at this again? This module has changed a lot since April and the report doens't apply anymore. Let us know if you run into new hurdles
