### ISSUE TITLE
Making resolve and IPLD service into a new package

### ISSUE THREAD

**Issue by nicola** [ipld/js-ipld-resolver#58]
I am now writing some very demo code to show IPLD.

I run into the following: `js-ipld` does not resolve a path query, so for example, given an object (that I have in memory), I can't use merkle paths to point to any attribute.
1. [ ] It would be great to have a function that resolves a path given a service (`resolve(service, path)`)
2. [ ] It would be great if we make an IPLD service that is dum - basically just a memory store, there is no need to run the entire IPFS

**Comment by diasdavid** [comment]
The IPLD Service uses the BlockStore and BlockStore can use any blob-store implementation (fs, memory, indexedDB, etc)

👍 for having the resolver as a separate package

**Comment by diasdavid** [comment]
From the chat in IRC, @nicola is looking to have an IPLD sandbox so that it is easy to attach an in memory IPLD service, without having to do the 'IPFS Repo -> IPFS Block Service -> IPFS Dag Service' dance.

**Comment by dignifiedquire** [comment]
The current interactions with the ipfs-repo are pretty minimal at this point, so we can abstract things out. 

We only use the blockservice, and from that we need three methods
- `getStream(key)`
- `putStream(cb)`
- `delete(key, cb)`

So we would move the majority of this code into something called `js-ipld-service` and this repo would look like this


```js

class IpfsIpldService extends IPLDService {
  constructor (blockservice) {
    super({
      getStream (key) {
        return blockservice.getStream(key, 'ipld')
      },

      putStream (cb) {
        return pull(
          pull.map((node) => new Block(node, 'ipld')),
          blockservice.putStream(),
          pull.onEnd(cb)
        )
      },
      
      delete (key, cb) {
        return blockservice.delete(key, cb)
      }
    })
  } 
}
```

**Comment by nicola** [comment]
This is the modularity I was looking for :)
And maybe taking out resolve!

**Comment by diasdavid** [comment]
@nicola let's chat during today's js-ipfs chat, you will like what is happening on https://github.com/ipld/js-ipld-resolver/pull/60 :) (also, I really want your input on it, getting super close)

**Comment by diasdavid** [comment]
This issue is no longer applicable. In fact the new version has what you were looking for, @nicola :)
