### ISSUE TITLE
Put many?

### ISSUE THREAD

**Issue by nicola** [ipld/js-ipld-resolver#79]
Is it possible to
- have a function (`.putAll` ?) when one could put many objects instead of just one?
- or have put to accept an array instead of a single object?

**Comment by diasdavid** [comment]
@nicola think of the ipld-resolver as the internal plumbing, look into ways to improve the DAG API https://github.com/ipfs/interface-ipfs-core/tree/master/API/dag which currently maps one to one with the IPLD resolver, but doesn't have to be :) 

Note, put is a pull stream, so you can put as many as you want.

**Comment by nicola** [comment]
Ok, putStream does what I need!
Perfect!
