### ISSUE TITLE
Usage of node `path.join` breaks IPLD paths on Windows

### ISSUE THREAD

**Issue by Expyron** [ipld/js-ipld-resolver#99]
joinPath [here](https://github.com/ipld/js-ipld-resolver/blob/master/src/index.js#L115) is returning the path separated by platform-specific path separators.

The code afterwards in the resolvers is expecting forward slashes, so it doesn't work on Windows platforms.

I suggest replacing all backslashes by slashes after joinPath on Windows platforms.

**Comment by diasdavid** [comment]
@Expyron that path is for IPLD Path which uses `/`, it should be no different in Windows.

**Comment by Expyron** [comment]
That's clear. I'm saying that this is not working properly on Windows.

When doing:
`ipfs.dag.get(cid, 'folder/file', callback)`

It works properly on Linux, but not on Windows. There's the part [here](https://github.com/ipld/js-ipld-resolver/blob/master/src/index.js#L120) that uses 'path.join()' which converts the path to 'folder\file' (with a backslash). IPLD resolvers don't understand that path with a backslash.

**Comment by diasdavid** [comment]
Ah! You are right, great catch! We need to keep using the _Linux version_, even on Windows. Would you like to patch this bug?

**Comment by richardschneider** [comment]
Fixed in PR #104
